# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-04 12:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20160424_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixname', models.CharField(max_length=10, unique=True)),
                ('amount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'prefix',
            },
        ),
        migrations.CreateModel(
            name='UserPrefixRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserPrefix')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_prefix_relation',
            },
        ),
        migrations.AddField(
            model_name='userprefix',
            name='childrens',
            field=models.ManyToManyField(through='account.UserPrefixRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userprefixrelation',
            unique_together=set([('prefix', 'user')]),
        ),
    ]
